### ISSUE TITLE
Get PMS color is not a function

### ISSUE THREAD

**Issue by larie438** [schroef/Illustrator-Scripts#2]
Hi,
I just installed your script. So, I am not sure if this is a bug or if I'm doing something wrong, but when I try to run the script, I get the following error:
Error 24: getPMSColor is not a function.
Line: 647
->
getPMSColor(item, item);

illustrator 2023

thanks

**Comment by schroef** [comment]
Are you using the script "renderSwatchLegend"?

Is it possible for me to get a simplified file your using so I can test?

**Comment by larie438** [comment]
Sorry for the late reply. Do you still need my file?

**Comment by larie438** [comment]
I hate being the bearer of bad news but with the latest version, I'm now getting the following error:
Error 48: File or folder does not exist.
Line: 1
-> #include "color.is>"

**Comment by schroef** [comment]
> I hate being the bearer of bad news but with the latest version, I'm now getting the following error:
> Error 48: File or folder does not exist.
> Line: 1
> -> #include "color.is>"

Yeah like is said, I seem to have broken something a while back. I know I was updating it, I was trying to make it work on selected path as well.

I tried a hotfix yesterday, but didn't work completely. So I'm gonna roll back a version and check where it went wrong.

**Comment by schroef** [comment]
@larie438 

Okay fixed it. I rolled back a bit. I guess i accidentally pushed a wip file. I tested it here with some files locally and works again.

Let me know if you find other issues

**Comment by larie438** [comment]
Works great! thanks
